#! /bin/sh

bspc rule -r "*"

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	3
bspc config window_gap          	15
bspc config top_padding				24
bspc config focus_follows_pointer 	true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Terminal desktop='^1'
# bspc rule -a Firefox desktop='^2'
# bspc rule -a Code desktop='^3'

~/.config/polybar/launch.sh
dunst &
picom &