#!/usr/bin/env sh

# Make sure bspwm removes all its rules for a clean restart
bspc rule -r "*"

# Start sxhkd if dead
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.dotfiles/sxhkd/sxhkdrc &

bspc monitor -d 1 2 3 4 5

# --- Windows --- #
# Colors
bspc config normal_border_color "#f8f8f8"
bspc config focused_border_color "#42b983"
bspc config active_border_color "#f8f800"
bspc config urgent_border_color "#f66"

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action_3 resize_corner

bspc config click_to_focus        true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false

# Gaps
bspc config border_width         3
bspc config window_gap           5

# Modes
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
