name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - uses: actions/checkout@v2
      - run: pacman -Syu git sudo
      - run: sh setup.sh

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh setup.sh
